services:
  backend:
    image: ghcr.io/holasoymartin25/senti2-backend:latest
    env_file:
      - ./senti2-backend/.env
    restart: unless-stopped

  reverb:
    image: ghcr.io/holasoymartin25/senti2-backend:latest
    env_file:
      - ./senti2-backend/.env
    entrypoint: ["php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8080"]
    depends_on:
      - backend
    restart: unless-stopped

  frontend:
    image: ghcr.io/holasoymartin25/senti2-frontend:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
      - reverb
    restart: unless-stopped
